module.exports = {
  extends: [
    'react-app',
    'plugin:@typescript-eslint/recommended',
    'plugin:react/recommended',
    'plugin:react/jsx-runtime',
    'plugin:jsx-a11y/recommended',
    'plugin:typescript-sort-keys/recommended',
    'plugin:import/recommended',
    'plugin:@tanstack/eslint-plugin-query/recommended',
  ],
  parser: '@typescript-eslint/parser',
  parserOptions: {
    project: ['tsconfig.json'],
  },
  plugins: ['sort-destructure-keys', 'sort-keys-fix', 'simple-import-sort', 'prefer-arrow', 'node', '@tanstack/query'],
  rules: {
    '@typescript-eslint/no-unnecessary-condition': 'error',
    '@typescript-eslint/array-type': ['error', { default: 'generic' }],
    '@typescript-eslint/explicit-module-boundary-types': 'off',
    '@typescript-eslint/method-signature-style': ['error', 'method'],
    '@typescript-eslint/naming-convention': [
      'error',
      {
        custom: { match: false, regex: '^Props$' },
        format: ['PascalCase'],
        selector: 'interface',
      },
    ],
    '@typescript-eslint/no-empty-interface': 'off',
    '@typescript-eslint/no-shadow': ['error'],
    'func-style': ['error'],
    'import/named': 'off',
    'import/no-unresolved': 'off',
    'jsx-a11y/no-autofocus': 'off',
    'jsx-a11y/no-onchange': 'off',
    'jsx-quotes': ['error', 'prefer-double'],
    'no-restricted-syntax': ['error', { message: 'Prefer named exports', selector: 'ExportDefaultDeclaration' }],
    'no-shadow': 'off',
    'node/no-process-env': 'error',
    'prefer-arrow/prefer-arrow-functions': ['error'],
    'prefer-template': 'error',
    quotes: ['error', 'single', { avoidEscape: true }],
    'react/destructuring-assignment': 'error',
    'react/function-component-definition': [
      'error',
      {
        namedComponents: 'arrow-function',
        unnamedComponents: 'arrow-function',
      },
    ],

    'react/jsx-boolean-value': 'error',
    'react/jsx-key': 'error',
    'react/jsx-no-bind': 'error',
    'react/jsx-sort-props': 'error',
    'react/no-array-index-key': 'error',
    'react/prop-types': 'off',
    'react/self-closing-comp': ['error', { component: true, html: false }],
    'simple-import-sort/exports': 'error',
    'simple-import-sort/imports': 'error',
    'sort-destructure-keys/sort-destructure-keys': 'error',
    'sort-keys-fix/sort-keys-fix': 'error',
    'sort-vars': 'error',
  },
  settings: {
    react: {
      version: '18.0.0',
    },
  },
};
